name: Integration Tests

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    paths:
      - 'apps/nestjs-backend/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration Tests - ${{ matrix.e2e.database-type }} ${{ matrix.e2e.shard }} ${{ matrix.runtime.mode }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [22.18.0]
        runtime:
          - mode: v1
            force-v2-all: ''
            computed-update-mode: ''
          - mode: v2
            force-v2-all: 'true'
            computed-update-mode: 'sync'
        e2e:
          - database-type: postgres
            shard: 1/4
          - database-type: postgres
            shard: 2/4
          - database-type: postgres
            shard: 3/4
          - database-type: postgres
            shard: 4/4
    env:
      CI: 1

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: ðŸ“¥ Monorepo install
        uses: ./.github/actions/pnpm-install

      - name: ðŸ§ª Run Tests
        env:
          CI: 1
          FORCE_V2_ALL: ${{ matrix.runtime.force-v2-all }}
          V2_COMPUTED_UPDATE_MODE: ${{ matrix.runtime.computed-update-mode }}
          VITEST_MAX_THREADS: 2
          VITEST_MIN_THREADS: 1
          VITEST_SHARD: ${{ matrix.e2e.shard }}
          VITEST_REPORTER: blob
        run: |
          make ${{ matrix.e2e.database-type }}.integration.test
          pnpm -F "@teable/backend" test-unit-cover
          pnpm -F "@teable/backend" merge-cover
          pnpm -F "@teable/backend" generate-cover

      - name: Coveralls Parallel
        uses: coverallsapp/github-action@v2
        with:
          flag-name: run-${{ join(matrix.*, '-') }}
          file: apps/nestjs-backend/coverage/nestjs-backend/clover.xml
          parallel: true

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
